Organisation_Details : 
{
  Business_Name = "Mon Entreprise";
  Business_Address = "Adresse Entreprise, Ville";
  Contact_Name = "Nom Responsable";
  Contact_Phone = "+261 XX XX XXX XX";
  Op_Tech_Name = "Technicien Effacement";
};
PDF_Certificate : 
{
  PDF_Enable = "ENABLED";
  PDF_Preview = "DISABLED";
};
Selected_Customer : 
{
  Customer_Name = "Not Applicable (CN)";
  Customer_Address = "Not Applicable (CA)";
  Contact_Name = "Not Applicable (CCN)";
  Contact_Phone = "Not Applicable (CP)";
};
